In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("train.csv")
df

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0              2.0  30.0  Female    39.0             14.0            5.0   
1              3.0  65.0  Female    49.0              1.0           10.0   
2              4.0  55.0  Female    14.0              4.0            6.0   
3              5.0  58.0    Male    38.0             21.0            7.0   
4              6.0  23.0    Male    32.0             20.0            5.0   
...            ...   ...     ...     ...              ...            ...   
440828    449995.0  42.0    Male    54.0             15.0            1.0   
440829    449996.0  25.0  Female     8.0             13.0            1.0   
440830    449997.0  26.0    Male    35.0             27.0            1.0   
440831    449998.0  28.0    Male    55.0             14.0            2.0   
440832    449999.0  31.0    Male    48.0             20.0            1.0   

        Payment Delay Subscription Type Contract Length  Total Spend  \
0                18.0          Standard          Annual       932.00   
1                 8.0             Basic         Monthly       557.00   
2                18.0             Basic       Quarterly       185.00   
3                 7.0          Standard         Monthly       396.00   
4                 8.0             Basic         Monthly       617.00   
...               ...               ...             ...          ...   
440828            3.0           Premium          Annual       716.38   
440829           20.0           Premium          Annual       745.38   
440830            5.0          Standard       Quarterly       977.31   
440831            0.0          Standard       Quarterly       602.55   
440832           14.0           Premium       Quarterly       567.77   

        Last Interaction  Churn  
0                   17.0    1.0  
1                    6.0    1.0  
2                    3.0    1.0  
3                   29.0    1.0  
4                   20.0    1.0  
...                  ...    ...  
440828               8.0    0.0  
440829               2.0    0.0  
440830               9.0    0.0  
440831               2.0    0.0  
440832              21.0    0.0  

[440833 rows x 12 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object 
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object 
 8   Contract Length    440832 non-null  object 
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB


In [6]:
df['Churn'].value_counts()

1.0    249999
0.0    190833
Name: Churn, dtype: int64

In [14]:
df.dropna(inplace=True)

In [16]:
df.isna().sum()

Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [8]:
df.drop(['CustomerID'],axis=1,inplace=True)

In [17]:
from sklearn.preprocessing import LabelEncoder

# Encode categorical variables
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [18]:
df

Age  Gender  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0       30.0       0    39.0             14.0            5.0           18.0   
1       65.0       0    49.0              1.0           10.0            8.0   
2       55.0       0    14.0              4.0            6.0           18.0   
3       58.0       1    38.0             21.0            7.0            7.0   
4       23.0       1    32.0             20.0            5.0            8.0   
...      ...     ...     ...              ...            ...            ...   
440828  42.0       1    54.0             15.0            1.0            3.0   
440829  25.0       0     8.0             13.0            1.0           20.0   
440830  26.0       1    35.0             27.0            1.0            5.0   
440831  28.0       1    55.0             14.0            2.0            0.0   
440832  31.0       1    48.0             20.0            1.0           14.0   

       Subscription Type Contract Length  Total Spend  Last Interaction  Churn  
0               Standard          Annual       932.00              17.0    1.0  
1                  Basic         Monthly       557.00               6.0    1.0  
2                  Basic       Quarterly       185.00               3.0    1.0  
3               Standard         Monthly       396.00              29.0    1.0  
4                  Basic         Monthly       617.00              20.0    1.0  
...                  ...             ...          ...               ...    ...  
440828           Premium          Annual       716.38               8.0    0.0  
440829           Premium          Annual       745.38               2.0    0.0  
440830          Standard       Quarterly       977.31               9.0    0.0  
440831          Standard       Quarterly       602.55               2.0    0.0  
440832           Premium       Quarterly       567.77              21.0    0.0  

[440832 rows x 11 columns]

In [19]:
from sklearn.preprocessing import LabelEncoder

# Encode categorical variables
label_encoder = LabelEncoder()
df['Contract Length'] = label_encoder.fit_transform(df['Contract Length'])
df['Subscription Type'] = label_encoder.fit_transform(df['Subscription Type'])
df

Age  Gender  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0       30.0       0    39.0             14.0            5.0           18.0   
1       65.0       0    49.0              1.0           10.0            8.0   
2       55.0       0    14.0              4.0            6.0           18.0   
3       58.0       1    38.0             21.0            7.0            7.0   
4       23.0       1    32.0             20.0            5.0            8.0   
...      ...     ...     ...              ...            ...            ...   
440828  42.0       1    54.0             15.0            1.0            3.0   
440829  25.0       0     8.0             13.0            1.0           20.0   
440830  26.0       1    35.0             27.0            1.0            5.0   
440831  28.0       1    55.0             14.0            2.0            0.0   
440832  31.0       1    48.0             20.0            1.0           14.0   

        Subscription Type  Contract Length  Total Spend  Last Interaction  \
0                       2                0       932.00              17.0   
1                       0                1       557.00               6.0   
2                       0                2       185.00               3.0   
3                       2                1       396.00              29.0   
4                       0                1       617.00              20.0   
...                   ...              ...          ...               ...   
440828                  1                0       716.38               8.0   
440829                  1                0       745.38               2.0   
440830                  2                2       977.31               9.0   
440831                  2                2       602.55               2.0   
440832                  1                2       567.77              21.0   

        Churn  
0         1.0  
1         1.0  
2         1.0  
3         1.0  
4         1.0  
...       ...  
440828    0.0  
440829    0.0  
440830    0.0  
440831    0.0  
440832    0.0  

[440832 rows x 11 columns]

In [20]:
X = df.drop('Churn', axis=1)
y = df['Churn']
X

Age  Gender  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0       30.0       0    39.0             14.0            5.0           18.0   
1       65.0       0    49.0              1.0           10.0            8.0   
2       55.0       0    14.0              4.0            6.0           18.0   
3       58.0       1    38.0             21.0            7.0            7.0   
4       23.0       1    32.0             20.0            5.0            8.0   
...      ...     ...     ...              ...            ...            ...   
440828  42.0       1    54.0             15.0            1.0            3.0   
440829  25.0       0     8.0             13.0            1.0           20.0   
440830  26.0       1    35.0             27.0            1.0            5.0   
440831  28.0       1    55.0             14.0            2.0            0.0   
440832  31.0       1    48.0             20.0            1.0           14.0   

        Subscription Type  Contract Length  Total Spend  Last Interaction  
0                       2                0       932.00              17.0  
1                       0                1       557.00               6.0  
2                       0                2       185.00               3.0  
3                       2                1       396.00              29.0  
4                       0                1       617.00              20.0  
...                   ...              ...          ...               ...  
440828                  1                0       716.38               8.0  
440829                  1                0       745.38               2.0  
440830                  2                2       977.31               9.0  
440831                  2                2       602.55               2.0  
440832                  1                2       567.77              21.0  

[440832 rows x 10 columns]

In [21]:
y

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ... 
440828    0.0
440829    0.0
440830    0.0
440831    0.0
440832    0.0
Name: Churn, Length: 440832, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
from sklearn.linear_model import LogisticRegression

# Logistic Regression Classifier
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

C:\Users\Waqas-Hussain\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [24]:
y_pred_lr = logistic_regression.predict(X_test)
y_pred_lr

array([1., 1., 0., ..., 0., 1., 0.])

In [25]:
pd.DataFrame({"Actual": y_test, "Predictions": y_pred_lr}).head(30)

Actual  Predictions
159565     1.0          1.0
127464     1.0          1.0
22398      1.0          0.0
99337      1.0          1.0
300997     0.0          0.0
380840     0.0          1.0
429228     0.0          0.0
395683     0.0          0.0
55619      1.0          0.0
82320      1.0          1.0
66309      1.0          1.0
394613     0.0          0.0
370478     0.0          0.0
422457     0.0          1.0
32582      1.0          1.0
31518      1.0          1.0
235949     1.0          1.0
77109      1.0          1.0
345665     0.0          1.0
306838     0.0          0.0
347091     0.0          0.0
206390     1.0          1.0
147041     1.0          1.0
425730     0.0          1.0
399153     0.0          0.0
434752     0.0          0.0
287332     0.0          0.0
277684     0.0          0.0
247424     1.0          1.0
410124     0.0          0.0

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Evalution
accuracy_lr = accuracy_score(y_test, y_pred_lr)
confusion_matrix_lr = confusion_matrix(y_test, y_pred_lr)

print("Accuracy : ", accuracy_lr)
print("Confusion Matrix...\n", confusion_matrix_lr)

Accuracy :  0.8486735399866163
Confusion Matrix...
 [[32134  5929]
 [ 7413 42691]]


In [27]:
from sklearn.linear_model import LogisticRegression

# Logistic Regression Classifier
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

C:\Users\Waqas-Hussain\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
from sklearn.tree import DecisionTreeClassifier

# Decision Tree Classifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)

y_pred_dt = decision_tree.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
confusion_matrix_dt = confusion_matrix(y_test, y_pred_dt)

print("Accuracy : ", accuracy_dt)
print("Confusion Matrix...\n", confusion_matrix_dt)

Accuracy :  0.99981852620595
Confusion Matrix...
 [[38059     4]
 [   12 50092]]


In [29]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest Classifier
random_forest = RandomForestClassifier()
random_forest.fit(X_train, y_train)

y_pred_rf = random_forest.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
confusion_matrix_rf = confusion_matrix(y_test, y_pred_rf)

print("Accuracy : ", accuracy_rf)
print("Confusion Matrix...\n", confusion_matrix_rf)

Accuracy :  0.9997504735331814
Confusion Matrix...
 [[38061     2]
 [   20 50084]]
